### ISSUE TITLE
auto-complete doesn't work

### ISSUE THREAD

**Issue by pastelInc** [jcollard/elm-mode#147] opened 2018-11-14 08:28 UTC
Hi, auto-complete did not work. Please help.

I expected `Debug.log` to be complemented.

![issue](https://user-images.githubusercontent.com/5408269/48469573-94f6a100-e832-11e8-8114-67f9805ca7ad.gif)

### Affected Package

20181109.2053 or earlier

### Minimal Reproduction

I prepared initial emacs environment.

1. prepare `init.el`
2. boot emacs
3. package-install elm-mode company company-quickhelp
4. add settings in `init.el`
5. reboot emacs
6. open `*.elm` file
7. try auto-complete

I tried in this `init.el`

```elisp
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives (cons "gnu" (concat proto "://elpa.gnu.org/packages/")))))
(package-initialize)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages (quote (company-quickhelp company elm-mode))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;;; appending settings
(company-quickhelp-mode)

(add-hook 'after-init-hook 'global-company-mode)

(add-to-list 'company-backends 'company-elm)
```

### My Environment

- macOS 10.12.x
- Emacs 26.1
- node.js 8.2.1
- elm 0.18.0
- elm-oracle 1.1.1

**Comment by pastelInc** [comment] 2018-11-14 08:46
Result of `M-x company-diag`

```elisp
Company 0.9.7

company-backends: (company-elm company-bbdb company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
	     (company-dabbrev-code company-gtags company-etags company-keywords)
	     company-oddmuse company-dabbrev)

Used backend: company-elm
Major mode: elm-mode
Prefix: "Debug."
Completions: none
```

**Comment by purcell** [comment] 2018-11-14 09:02
Duplicate of #142.

**Closed by purcell** 2018-11-14 09:02 UTC
