### ISSUE TITLE
Indent cycle

### ISSUE THREAD

**Issue by hiaw** [jcollard/elm-mode#70] opened 2016-04-26 20:48 UTC
I find emacs keep crashing when I try to copy and paste in Elm. This is my view code and I want to move all the styles to the bottom of the file. 

````
view : Signal.Address Action -> Model -> Ui.NativeUi
view address model =
  NativeUi.Elements.view
    [ componentStyle ]
    [ image
        [ imageStyle
        , source model.image
        ]
        []
    , NativeUi.Elements.view
        [ Ui.style [ Style.flex 1 ] ]
        [ text
            [ Ui.style
                [ Style.fontSize 20
                , Style.marginBottom 8
                , Style.textAlign "center"
                ]
            ]
            [ Ui.string model.title ]
        , text
            [ Ui.style
                [ Style.textAlign "center"
                ]
            ]
            [ Ui.string model.year ]
        ]
    ]
````

So when I try to cut and paste the following code to the bottom of file, it goes into "Indent cycle (2)" (infinite loop I guess) and Emacs just stop responding. I had to kill emacs. (I'm using spacemacs)

````
Ui.style
                [ Style.fontSize 20
                , Style.marginBottom 8
                , Style.textAlign "center"
                ]
````

Thanks.

**Comment by laduke** [comment] 2016-05-23 02:40
this has been happening to me too. Using spacemacs as well. Is there a way to interrupt it without force quitting?

**Comment by Bogdanp** [comment] 2016-05-23 05:41
Have you tried bringing this up in the Spacemacs repo? I'm unable to reproduce the issue unfortunately and I don't use Spacemacs.

> Is there a way to interrupt it without force quitting?

`C-g` should be able to interrupt any indentation code.

**Comment by Bogdanp** [comment] 2016-09-03 13:26
I'm closing this since I've been unable to reproduce the issue and there hasn't been any activity since May.

**Closed by Bogdanp** 2016-09-03 13:26 UTC
